ARG DISTROLESS_IMAGE
FROM $DISTROLESS_IMAGE AS distroless

FROM mcr.microsoft.com/azurelinux/base/core:3.0@sha256:7caf6bede8a3fa62340581a6e5409ede9564b6866d18143ffd0b691c8f2cfcfc

COPY --from=distroless / /rootfs
WORKDIR /rootfs
