name: 'Check Markdown Links'

on:
  pull_request:
    paths:
      - "**/*.md"

permissions:
  pull-requests: read

jobs:
  check-markdown-links:
    # https://github.com/UmbrellaDocs/action-linkspector/issues/32
    # Upgrade to `ubuntu-latest` when resolved
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Check markdown links
        uses: umbrelladocs/action-linkspector@de84085e0f51452a470558693d7d308fbb2fa261 # v1
        with:
          config_file: .github/linters/.linkspector.yml
          fail_on_error: true
          filter_mode: nofilter
