name: Fork and Run Renovate

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  fork-and-renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: Create Fork
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          gh repo fork mthalman/dotnet-docker
          //echo "fork-full-name=$(gh repo view mthalman/dotnet-docker --json parent --jq '.parent.owner.login + \"/\" + .parent.name')" >> $GITHUB_ENV

      # - name: Checkout Fork
      #   uses: actions/checkout@v2
      #   with:
      #     repository: ${{ env.fork-full-name }}

      # - name: Run Renovate
      #   uses: renovatebot/github-action@v41.0.13
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
